### PR TITLE
[DEV] Adding notes about the native commands 

### LINKED ISSUE #29: Extract all native tool commands from the logs
We can create an alternative Nextflow native version of this workflow using the knowledge of the underlying commands.

### PR DESCRIPTION
**Pull request by Mxrcon**
Hey @abhi18av here goes my notes with tall the commands mentioned on the standard output, the commands using parallel and full seems to be the same, but there are steps that uses mtbseq tools, not external tools. I just wrote what mtbseq does in the analysis process sense.

This Pull Request closes #29 

Feel free to discuss these notes, and also to add yours. If you think that there's something missing, please tell me and I'll proceed with the changes,

Hope we have a merge!

### CODE REVIEW

**Review by abhi18av — CHANGES_REQUESTED** [review]
This is a great start @Mxrcon , thanks!

I do have a couple of changes requests 

1. Export the `org` file to `md` so that the repo is consistent with documentation formats
2. Create a header for `TBFull` 


Also, could you please another task to enhance this file later with the exact commands from other modules as well. Yes, the `TBFull` command convers this but perhaps we might be able to gain some inside with individual modules later on.

**Comment by Mxrcon** [comment]
> 1.

Ok I'll add that

> 2.

I actually have notes for the process for parallel run. I'll add notes about each process.

**Comment by Mxrcon** [comment]
hey! @abhi18av I've proceeded with the changes as requested, now we have a markdown file with the required content

**Review by abhi18av — APPROVED** [review]
Thanks for this @Mxrcon , I'm merging this now and we can improve this later on.

**Pull request merged**
